In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
import math 

from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [29]:
from sklearn.datasets import fetch_openml
dataset = fetch_openml(name='boston', version=1, parser='auto')
print("Số chiều dữ liệu input: ", dataset.data.shape)
print("Số chiều dữ liệu target: ", dataset.target.shape)
print()

print("5 mẫu dữ liệu đầu tiên:")
print("input: ", dataset.data[:5])
print("target: ",dataset.target[:5])

Số chiều dữ liệu input:  (506, 13)
Số chiều dữ liệu target:  (506,)

5 mẫu dữ liệu đầu tiên:
input:        CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  PTRATIO  \
0  0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0     15.3
1  0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0     17.8
2  0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0     17.8
3  0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0     18.7
4  0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0     18.7

        B  LSTAT
0  396.90   4.98
1  396.90   9.14
2  392.83   4.03
3  394.63   2.94
4  396.90   5.33
target:  0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: MEDV, dtype: float64

In [38]:
from sklearn.model_selection import train_test_split
X=dataset.data
y=dataset.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state = 51)

In [39]:
regr=linear_model.LinearRegression()

In [43]:
def linear_regression(X_train,y_train):
    X_train = np.asarray(X_train, dtype=float)
    y_train = np.asarray(y_train, dtype=float)
    one = np.ones((X_train.shape[0],1))
    Xbar = np.concatenate((one, X_train), axis = 1)
    A = np.dot(Xbar.T, Xbar)
    b = np.dot(Xbar.T, y_train)
    w_lr = np.dot(np.linalg.pinv(A), b)
    coef = w_lr[1:]
    intercept = w_lr[0]
    return coef, intercept

In [44]:
def predict(intercept, coef, X_test):
    return np.dot(X_test, coef) + intercept

In [45]:
regr.fit(X_train,y_train)
print("[w1, ... w_n] = ", regr.coef_)
print("w0 = ", regr.intercept_)

[w1, ... w_n] =  [-8.37128384e-02  3.29737790e-02  9.28376082e-03  2.75531283e+00
 -1.67741685e+01  4.13414996e+00  5.23358017e-03 -1.30776093e+00
  2.66294939e-01 -8.91756423e-03 -9.96988473e-01  9.69473178e-03
 -5.28576519e-01]
w0 =  32.68023867185811

In [46]:
coef, intercept=linear_regression(X_train=X_train, y_train=y_train)
print ('coef=',coef)
print ('intercept=', intercept)

coef= [-8.37128384e-02  3.29737790e-02  9.28376082e-03  2.75531283e+00
 -1.67741685e+01  4.13414996e+00  5.23358017e-03 -1.30776093e+00
  2.66294939e-01 -8.91756423e-03 -9.96988473e-01  9.69473179e-03
 -5.28576519e-01]
intercept= 32.680238668614685

In [49]:
y_pred = regr.predict(np.asarray(X_test, dtype=float))
print(y_pred)
pd.DataFrame(data=np.array([y_test, y_pred,abs(y_test-y_pred)]).T,columns=["Thực tế", "Dự đoán", "Lệch"])

[14.1045114  14.19774219 41.25953662 20.07258994 21.39655938 19.08540464
 41.00700739 13.55577859 24.76213821 17.38451725 30.26474556 35.7695295
 20.89660845 13.36675887 11.51491653 36.44420552 22.53614253 16.31656198
 20.2472769  16.78196178 16.35250127 22.48612309 36.65369332 23.58655522
 10.00312286 26.81297026 18.46784221 10.09983805  2.97130046 23.02018986
  7.71470442 17.15224199 21.25655526 20.56105954 21.3305415   5.61963021
 16.64348774 19.45395289 20.90320165 35.24069524 34.18423896 20.03515291
 30.67713956 20.16278628 24.46212836 19.39328002 27.45992538 19.73028442
 23.73936417 32.88618017 28.55924823 13.50451139 19.37048115 34.83132428
 24.04053385 34.40551869 19.41008249 18.83837192 33.64485097 17.03085006
 19.99330488 13.09392747 32.45664146 26.73939315 17.20678286 16.05242512
 20.17444259 30.91174893 32.06806699 15.30695032 24.79489825 18.14876352
 13.24435862 20.27331012 13.48316685 12.19594722 24.85876687 18.95271719
 17.17229243 42.21969832 35.71901431 26.43629013 17.03022394 38.78299949
 13.43529778 32.88527948 14.74182013 25.55023018 20.6666847  23.19732369
 30.17331129 17.34168971 38.46361191 13.70070268 20.17277279 17.42834924
 34.72574949 21.39646421 20.1558721  23.36968801 24.99645084 32.79407355]

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

     Thực tế    Dự đoán      Lệch
0       11.5  14.104511  2.604511
1       11.0  14.197742  3.197742
2       50.0  41.259537  8.740463
3       23.0  20.072590  2.927410
4       21.1  21.396559  0.296559
..       ...        ...       ...
97      23.3  21.396464  1.903536
98      27.5  20.155872  7.344128
99      24.4  23.369688  1.030312
100     30.1  24.996451  5.103549
101     27.0  32.794074  5.794074

[102 rows x 3 columns]

In [53]:
y_test_linear=predict(intercept=intercept, coef=coef, X_test=np.asarray(X_test, dtype=float))
print (y_test_linear)
pd.DataFrame(data=np.array([y_test, y_test_linear,abs(y_test-y_test_linear)]).T,columns=["Thực tế", "Dự đoán", "Lệch"])

[14.1045114  14.19774219 41.25953662 20.07258994 21.39655938 19.08540464
 41.00700739 13.55577859 24.76213821 17.38451725 30.26474556 35.7695295
 20.89660845 13.36675887 11.51491653 36.44420552 22.53614253 16.31656198
 20.2472769  16.78196179 16.35250127 22.48612309 36.65369332 23.58655522
 10.00312286 26.81297026 18.46784221 10.09983805  2.97130046 23.02018986
  7.71470442 17.15224199 21.25655526 20.56105954 21.3305415   5.61963021
 16.64348774 19.45395289 20.90320165 35.24069524 34.18423896 20.03515291
 30.67713956 20.16278628 24.46212836 19.39328002 27.45992538 19.73028442
 23.73936417 32.88618017 28.55924823 13.50451139 19.37048115 34.83132428
 24.04053385 34.40551869 19.41008249 18.83837192 33.64485097 17.03085006
 19.99330488 13.09392747 32.45664146 26.73939315 17.20678286 16.05242512
 20.17444259 30.91174893 32.06806699 15.30695032 24.79489825 18.14876352
 13.24435862 20.27331012 13.48316685 12.19594722 24.85876687 18.95271719
 17.17229243 42.21969832 35.71901431 26.43629013 17.03022394 38.78299949
 13.43529778 32.88527948 14.74182013 25.55023018 20.6666847  23.19732369
 30.17331129 17.34168971 38.46361191 13.70070268 20.17277279 17.42834924
 34.72574949 21.39646421 20.1558721  23.36968801 24.99645084 32.79407355]

     Thực tế    Dự đoán      Lệch
0       11.5  14.104511  2.604511
1       11.0  14.197742  3.197742
2       50.0  41.259537  8.740463
3       23.0  20.072590  2.927410
4       21.1  21.396559  0.296559
..       ...        ...       ...
97      23.3  21.396464  1.903536
98      27.5  20.155872  7.344128
99      24.4  23.369688  1.030312
100     30.1  24.996451  5.103549
101     27.0  32.794074  5.794074

[102 rows x 3 columns]

In [55]:
loss = math.sqrt(mean_squared_error(y_test, y_pred))
print("lỗi :",loss)

lỗi : 4.922403844399777

In [56]:
loss = math.sqrt(mean_squared_error(y_test, y_test_linear))
print("lỗi :",loss)

lỗi : 4.922403844421725